### ISSUE TITLE
Improve comment block annotation parsing

### ISSUE THREAD

**Issue by c9s** [c9s/c6#56]
```css
@font-face {
  font-family: MyGentium;
  src: local(Gentium Bold),    /* should ignore */
       local(Gentium-Bold),    /* should ignore */
       url(GentiumBold.woff);  /* annotation of this declaration */
  font-weight: bold;
}
```

```css
@font-face {
  /* annotation of the font-family declaration */
  font-family: MyGentium;
  font-weight: bold;
}
```

```css
  /* annotation of the font-face statement */
@font-face {
  font-family: MyGentium;
  font-weight: bold;
}
```
